users/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('usersd.urls', namespace='usersd')),
    path('admin/', admin.site.urls),
]

usersd/urls.py
from django.urls import path
from . import views

app_name = 'usersd'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_views, name='profile'),
    path('account-details/', views.account_details, name='account_details'),
    path('edit-account-details/', views.edit_account_details, name='edit_account_details'),
    path('update-account-details/', views.updata_account_details, name='update_account_details'),
    path('logout/', views.logout_view, name='logout'),
]

usersd/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, \
    BaseUserManager
from django.utils.html import strip_tags



class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('The email field must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_staff=True')
        
        return self.create_user(email, first_name, last_name, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, max_length=66)
    first_name = models.CharField(max_length=66)
    last_name = models.CharField(max_length=66)
    address1 = models.CharField(max_length=128, blank=True, null=True)
    address2 = models.CharField(max_length=128, blank=True, null=True)
    city = models.CharField(max_length=128, blank=True, null=True)
    country = models.CharField(max_length=128, blank=True, null=True)
    province = models.CharField(max_length=128, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    # marketing consent1&2 podtverjdenie za reklamu (rassilku) cherez email!
    marketing_consent1 = models.BooleanField(default=False)
    marketing_consent2 = models.BooleanField(default=False)
    # -----------------------------
    username = models.CharField(max_length=150, unique=True, null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']


    def __str__(self):
        return self.email
    
    def clean(self):
        for field in ['address1', 'address2', 'city', 'country', 'province',
                        'postal_code', 'phone']:
            value = getattr(self, field)
            if value:
                setattr(self, field, strip_tags(value))

usersd/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, authenticate
from django.utils.html import strip_tags
from django.core.validators import RegexValidator



User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=66,
                             widget=forms.EmailInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your email'}))
    first_name = forms.CharField(required=True, max_length=50,
                                 widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your first name'}))
    last_name = forms.CharField(required=True, max_length=50,
                                 widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your last name'}))
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your password'}))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'class': 'input-register form-control', 'placeholder': 'Confirm your password'}))
    marketing_consent1 = forms.BooleanField(required=False,
                                            label="I agree to receive commercial, promotional and marketing communications.",
                                            widget=forms.CheckboxInput(attrs={'class': 'checkbox-input-register'}))
    marketing_consent2 = forms.BooleanField(required=False,
                                            label="I agree to receive personalized commercial communications.",
                                            widget=forms.CheckboxInput(attrs={'class': 'checkbox-input-register'}))
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',
                  'marketing_consent1', 'marketing_consent2')
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is already in use.')
        return email
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = None
        user.marketing_consent1 = self.cleaned_data['marketing_consent1']
        user.marketing_consent2 = self.cleaned_data['marketing_consent2']
        if commit:
            user.save()

        return user



class CustomUserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Email',
                               widget=forms.TextInput(attrs={'autofocus': True, 'class': 'input-register form-control', 'placeholder': 'Your email'}))
    password = forms.CharField(
        label='Password',
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'input-register form-control', 'placeholder': 'Your Password'}))


    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(self.request, username=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError('Invalid email or password.')
            elif not self.user_cache.is_active:
                raise forms.ValidationError('This account is inactive.')
        return self.cleaned_data



class CustomUserUpdateForm(forms.ModelForm):
    phone = forms.CharField(
        required=False,
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', "Enter a valid phone number.")],
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your phone number'})
    )
    first_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your first name'})
    )
    last_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your last name'})
    )
    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your email'})
    )


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'address1', 'address2',
                  'city', 'country', 'province', 'postal_code', 'phone')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'input-register form-control', 
                                             'placeholder': 'Your email'}),
            'first_name': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                 'placeholder': 'Your first name'}),
            'last_name': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                'placeholder': 'Your last name'}),
            'address1': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Address line 1'}),
            'address2': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Address line 2'}),
            'city': forms.TextInput(attrs={'class': 'input-register form-control', 
                                           'placeholder': 'Your city'}),
            'country': forms.TextInput(attrs={'class': 'input-register form-control', 
                                              'placeholder': 'Your country'}),
            'province': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Your province'}),
            'postal_code': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                  'placeholder': 'Your postal code'}),
        }

    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('This email is already in use.')
        return email
    

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('email'):
            cleaned_data['email'] = self.instance.email

        for field in ['address1', 'address2', 'city', 'country', 'province',
                        'postal_code', 'phone']:
            if cleaned_data.get(field):
                cleaned_data[field] = strip_tags(cleaned_data[field])

        return cleaned_data

usersd/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserLoginForm, CustomUserUpdateForm
from .models import CustomUser



def register(request):
    if request.method == 'POST':
        form =  CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('usersd:profile')
    else:
        form = CustomUserCreationForm()
    return render(request, 'usersd/register.html', {'form': form})
    

def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('usersd:profile')
    else:
        form = CustomUserLoginForm()
    return render(request, 'usersd/login.html', {'form': form})
    

@login_required
def profile_views(request):
    return render(request, 'usersd/profile.html', {'user': request.user})


@login_required
def account_details(request):
    user = CustomUser.objects.get(id=request.user.id)
    return render(request, 'usersd/partials/account_details.html',
                  {'user': user})

@login_required
def edit_account_details(request):
    form = CustomUserUpdateForm(instance=request.user)
    return render(request, 'usersd/partials/account_details.html',
                  {'user': request.user, 'form': form})


@login_required
def updata_account_details(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.clean()
            user.save()
            return render(request, 'usersd/partials/account_details.html', {'user': user})
        else:
            return render(request, 'usersd/partials/account_details.html', {'user': user})
    return render(request, 'usersd/partials/account_details.html', {'user': user})


def logout_view(request):
    logout(request)
    return redirect('usersd:register')

usersd/templates/usersd/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

usersd/templates/usersd/login.html
{% extends 'usersd/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <h1>Log In</h1>
    <form method="post" class="reg-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Email</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error">{{ form.username.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password }}
            {% if form.password.errors %}
                <div class="error">{{ form.password.errors }}</div>
            {% endif %}
        </div>
        <button type="submit">Log In</button>
        <a href="{% url 'usersd:register' %}" class="link">Don't have an account? Register</a>
    </form>
{% endblock %}

usersd/templates/usersd/profile.html
{% extends 'usersd/base.html' %}

{% block title %}Your Profile{% endblock %}

{% block content %}
    <h1>Hi, {{ request.user.first_name|upper }} {{ request.user.last_name|upper }}</h1>
    <div class="profile-section">
        <h2>Account Details</h2>
        <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
        <p>{{ request.user.email }}</p>
        <p>{{ request.user.country|default:"Not specified" }}</p>
        <button hx-get="{% url 'usersd:edit_account_details' %}" 
                hx-target="#account-details-content" 
                hx-swap="innerHTML">
            Edit
        </button>
        <div id="account-details-content"></div>
    </div>
    <a href="{% url 'usersd:logout' %}" class="link">Log Out</a>
{% endblock %}

usersd/templates/usersd/register.html
{% extends 'usersd/base.html' %}

{% block title %}Create Account{% endblock %}

{% block content %}
    <h1>Create Account</h1>
    <form method="post" class="reg-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.first_name.id_for_label }}">First Name</label>
            {{ form.first_name }}
            {% if form.first_name.errors %}
                <div class="error">{{ form.first_name.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.last_name.id_for_label }}">Last Name</label>
            {{ form.last_name }}
            {% if form.last_name.errors %}
                <div class="error">{{ form.last_name.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="error">{{ form.email.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.password1.id_for_label }}">Password</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="error">{{ form.password1.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="error">{{ form.password2.errors }}</div>
            {% endif %}
        </div>
        <div class="checkbox-form">
            {{ form.marketing_consent1 }}
            <label for="{{ form.marketing_consent1.id_for_label }}">
                I agree to receive commercial communications.
            </label>
            {% if form.marketing_consent1.errors %}
                <div class="error">{{ form.marketing_consent1.errors }}</div>
            {% endif %}
        </div>
        <div class="checkbox-form">
            {{ form.marketing_consent2 }}
            <label for="{{ form.marketing_consent2.id_for_label }}">
                I agree to receive personalized communications.
            </label>
            {% if form.marketing_consent2.errors %}
                <div class="error">{{ form.marketing_consent2.errors }}</div>
            {% endif %}
        </div>
        <button type="submit">Create</button>
        <a href="{% url 'usersd:login' %}" class="link">Already registered? Log in</a>
    </form>
{% endblock %}